// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKl6bBb-o0YxDy74ULC9wq7NtU6BWxO0A',
    appId: '1:897081432580:web:301321ed7a659301bd7351',
    messagingSenderId: '897081432580',
    projectId: 'authtutorial1-e78bd',
    authDomain: 'authtutorial1-e78bd.firebaseapp.com',
    storageBucket: 'authtutorial1-e78bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCARKGgMsLyhIphAvC1MzhKoAtJr8WAR9E',
    appId: '1:897081432580:android:b28d7820bcb061febd7351',
    messagingSenderId: '897081432580',
    projectId: 'authtutorial1-e78bd',
    storageBucket: 'authtutorial1-e78bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArLpBSannkKan-FMzEGJqMLXSFK4xEfAw',
    appId: '1:897081432580:ios:f1b82f4464d8c8f8bd7351',
    messagingSenderId: '897081432580',
    projectId: 'authtutorial1-e78bd',
    storageBucket: 'authtutorial1-e78bd.appspot.com',
    iosBundleId: 'com.example.theWall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArLpBSannkKan-FMzEGJqMLXSFK4xEfAw',
    appId: '1:897081432580:ios:f1b82f4464d8c8f8bd7351',
    messagingSenderId: '897081432580',
    projectId: 'authtutorial1-e78bd',
    storageBucket: 'authtutorial1-e78bd.appspot.com',
    iosBundleId: 'com.example.theWall',
  );
}
